# Generated by Django 5.2.3 on 2025-06-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonProductSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(help_text='The Amazon Standard Identification Number.', max_length=20, unique=True)),
                ('product_title', models.CharField(blank=True, max_length=255)),
                ('affiliate_url', models.URLField(blank=True, max_length=2048)),
                ('image_url', models.URLField(blank=True, max_length=2048)),
                ('price', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Amazon Product Snippets',
            },
        ),
    ]
